--liquibase formatted sql

--changeSet skryagin:1
CREATE TABLE additional_properties
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(255)
);

CREATE TABLE product_types
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(255)
);

CREATE TABLE products
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    serial_number           VARCHAR(255),
    manufacturer            VARCHAR(255),
    price                   FLOAT(53),
    quantity                INTEGER,
    additional_property_value VARCHAR(255),
    product_type_id         BIGINT REFERENCES product_types,
    additional_property_id  BIGINT REFERENCES additional_properties
);
